import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BookOpen, Bookmark, CheckCircle2, CircleUserRound, Compass, LogIn, LogOut, Plus, Search, Sparkles, Star, Trophy, X } from 'lucide-react'
import { supabase, supabaseConfigured } from './supabase'
import { enrichWithWikipedia, searchBooks } from './api'
import './styles.css'

const demoBooks=[
{id:'demo1',title:'O Hobbit',author:'J. R. R. Tolkien',cover_url:'https://covers.openlibrary.org/b/id/6979861-L.jpg',total_pages:310,current_page:176,status:'reading',rating:null,notes:'Estou curtindo bastante a aventura.',priority:'normal',summary:'Um hobbit é envolvido em uma grande aventura rumo à Montanha Solitária.'},
{id:'demo2',title:'1984',author:'George Orwell',cover_url:'https://covers.openlibrary.org/b/id/7222246-L.jpg',total_pages:328,current_page:0,status:'future',rating:null,notes:'',priority:'high',summary:'Romance distópico sobre vigilância, poder e controle social.'},
{id:'demo3',title:'O Pequeno Príncipe',author:'Antoine de Saint-Exupéry',cover_url:'https://covers.openlibrary.org/b/id/108684-L.jpg',total_pages:96,current_page:96,status:'completed',rating:5,notes:'Leitura que quero revisitar.',priority:'low',summary:'Uma narrativa poética sobre amizade, afeto e olhar para o essencial.'}]
const pct=b=>b.total_pages?Math.min(100,Math.round(Number(b.current_page||0)/Number(b.total_pages)*100)):0

function App(){
const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[authMode,setAuthMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMessage,setAuthMessage]=useState('')
const [tab,setTab]=useState('dashboard'),[books,setBooks]=useState(supabaseConfigured?[]:demoBooks),[query,setQuery]=useState(''),[results,setResults]=useState([]),[searching,setSearching]=useState(false),[modal,setModal]=useState(false),[selected,setSelected]=useState(null),[toast,setToast]=useState('')
useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[])
useEffect(()=>{if(session?.user)loadBooks()},[session?.user?.id])
useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(t)}},[toast])
async function loadBooks(){const {data,error}=await supabase.from('books').select('*').order('updated_at',{ascending:false});if(error)setToast(error.message);else setBooks(data||[])}
async function auth(e){e.preventDefault();setAuthMessage('');const r=authMode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)setAuthMessage(r.error.message);else if(authMode==='signup')setAuthMessage('Conta criada. Confira seu e-mail se a confirmação estiver ativa.')}
async function search(e){e.preventDefault();if(!query.trim())return;setSearching(true);try{setResults(await searchBooks(query))}catch(err){setToast(err.message)}finally{setSearching(false)}}
async function importBook(b){setSearching(true);let w=null;try{w=await enrichWithWikipedia(b.title,b.author)}catch{}setSelected({title:b.title,author:b.author,isbn:b.isbn,cover_url:b.coverUrl||w?.thumbnail,summary:w?.summary,wikipedia_url:w?.wikipediaUrl,total_pages:b.totalPages,current_page:0,status:'future',priority:'normal',notes:'',rating:null});setResults([]);setModal(true);setSearching(false)}
async function save(form){const p={...form,total_pages:form.total_pages?Number(form.total_pages):null,current_page:form.current_page?Number(form.current_page):0,rating:form.status==='completed'&&form.rating!==''?Number(form.rating):null,started_at:form.started_at||null,completed_at:form.status==='completed'?(form.completed_at||null):null,user_id:session?.user?.id};if(!p.title?.trim()){setToast('Informe o título do livro.');return}if(p.total_pages&&p.current_page>p.total_pages)p.current_page=p.total_pages;if(!supabaseConfigured){setBooks(x=>selected?.id?x.map(b=>b.id===selected.id?{...b,...p}:b):[{...p,id:'demo'+Date.now()},...x]);setModal(false);setToast('Livro salvo.');return}const r=selected?.id?await supabase.from('books').update(p).eq('id',selected.id):await supabase.from('books').insert(p);if(r.error)setToast(r.error.message);else{setModal(false);setToast('Livro salvo.');loadBooks()}}
async function update(id,p){if(!supabaseConfigured){setBooks(x=>x.map(b=>b.id===id?{...b,...p}:b));return}const r=await supabase.from('books').update(p).eq('id',id);if(r.error)setToast(r.error.message);else loadBooks()}
async function remove(id){if(!confirm('Excluir este livro?'))return;if(!supabaseConfigured){setBooks(x=>x.filter(b=>b.id!==id));return}const r=await supabase.from('books').delete().eq('id',id);if(r.error)setToast(r.error.message);else loadBooks()}
const reading=books.filter(b=>b.status==='reading'),future=books.filter(b=>b.status==='future'),completed=books.filter(b=>b.status==='completed')
const pages=books.reduce((s,b)=>s+Number(b.current_page||0),0),xp=pages+completed.length*120+reading.reduce((s,b)=>s+pct(b)*2,0),level=Math.floor(xp/500)+1
const avg=completed.length?(completed.reduce((s,b)=>s+Number(b.rating||0),0)/completed.length).toFixed(1):'—'
if(loading)return <div className="loading">Carregando seu universo de leitura…</div>
if(supabaseConfigured&&!session)return <Auth {...{authMode,setAuthMode,email,setEmail,password,setPassword,authMessage,auth}}/>
const nav=[['dashboard','Visão geral',Compass],['reading','Estou lendo',BookOpen],['future','Futuras leituras',Bookmark],['completed','Concluídos',CheckCircle2]]
const title={dashboard:'Visão geral',reading:'Estou lendo',future:'Futuras leituras',completed:'Livros concluídos'}[tab]
const list=tab==='reading'?reading:tab==='future'?future:tab==='completed'?completed:[]
return <div className="shell"><aside className="side"><div className="brand"><div className="logo"><BookOpen/></div><div><b>Reading Nexus</b><small>painel pessoal</small></div></div><nav>{nav.map(([id,label,I])=><button className={tab===id?'nav active':'nav'} onClick={()=>setTab(id)} key={id}><I size={18}/><span>{label}</span><em>{id==='reading'?reading.length:id==='future'?future.length:id==='completed'?completed.length:''}</em></button>)}</nav><div className="sideBottom"><div className="level"><span>Nível {level}</span><b>{xp} XP</b><div className="bar"><i style={{width:(xp%500)/5+'%'}}/></div><small>{500-xp%500} XP para o próximo nível</small></div><div className="user"><CircleUserRound size={19}/><span>{session?.user?.email||'Modo demonstração'}</span></div>{supabaseConfigured&&<button className="ghost" onClick={()=>supabase.auth.signOut()}><LogOut size={15}/> Sair</button>}</div></aside>
<main><header><div><label>CENTRAL DE LEITURA</label><h1>{tab==='dashboard'?'Olá, '+(session?.user?.email?.split('@')[0]||'Artur')+'.':title}</h1><p>{tab==='dashboard'?'Seu progresso, metas e a próxima aventura.':tab==='reading'?'Acompanhe exatamente onde você parou.':tab==='future'?'Sua fila de próximas aventuras.':'Tudo o que você já conquistou.'}</p></div><button className="primary" onClick={()=>{setSelected(null);setModal(true)}}><Plus size={18}/> Adicionar livro</button></header>
<section className="search"><div className="searchLabel"><Sparkles size={16}/> Adicionar a partir da internet</div><form onSubmit={search}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Título, autor ou ISBN…"/><button disabled={searching}>{searching?'Pesquisando…':'Pesquisar'}</button></form>{results.length>0&&<div className="results">{results.map((r,i)=><button key={i} onClick={()=>importBook(r)}><Cover src={r.coverUrl}/><span><b>{r.title}</b><small>{r.author}{r.year?' · '+r.year:''}</small></span><Plus size={17}/></button>)}</div>}</section>
{tab==='dashboard'?<Dashboard {...{books,reading,future,completed,pages,avg,level,xp,setTab,setSelected,setModal}}/>:<>{list.length?<div className="grid">{list.map(b=><BookCard key={b.id} book={b} update={update} remove={remove} edit={()=>{setSelected(b);setModal(true)}}/> )}</div>:<Empty tab={tab} onAdd={()=>{setSelected(null);setModal(true)}}/>}</>}
</main>{modal&&<BookModal book={selected} close={()=>setModal(false)} save={save}/>} {toast&&<div className="toast">{toast}</div>}</div>
}

function Dashboard({reading,future,completed,pages,avg,level,xp,setTab,setSelected,setModal}){const current=reading[0],ach=completed.length>=1?'Primeiro livro concluído':pages>=100?'100 páginas lidas':'Comece sua jornada';return <><div className="stats"><Stat icon={BookOpen} label="Estou lendo" value={reading.length}/><Stat icon={Bookmark} label="Na fila" value={future.length}/><Stat icon={CheckCircle2} label="Concluídos" value={completed.length}/><Stat icon={Star} label="Média" value={avg}/></div><div className="dash"><section className="card hero"><label>LEITURA ATUAL</label>{current?<div className="current"><Cover src={current.cover_url}/><div><h2>{current.title}</h2><p>{current.author}</p><div className="progressText"><b>{pct(current)}%</b><span>{current.current_page||0} / {current.total_pages||'—'} páginas</span></div><div className="bar big"><i style={{width:pct(current)+'%'}}/></div><button className="secondary" onClick={()=>setTab('reading')}>Continuar leitura</button></div></div>:<EmptyMini text="Nenhum livro em andamento. Escolha uma aventura." onClick={()=>setTab('future')}/>}</section><section className="card"><div className="cardHead"><div><label>PRÓXIMAS LEITURAS</label><h3>Sua fila</h3></div><span>{future.length}</span></div>{future.slice(0,4).map(b=><button className="mini" key={b.id} onClick={()=>{setSelected(b);setModal(true)}}><Cover src={b.cover_url}/><span><b>{b.title}</b><small>{b.author}</small></span></button>)}{!future.length&&<p className="muted">Sua fila está vazia.</p>}</section></div><div className="achievement"><div><label>CONQUISTA</label><h3>{ach}</h3><p>Nível {level} · {xp} XP. Continue acumulando páginas e histórias.</p></div><div className="badge"><Trophy size={20}/><span>Progresso</span></div></div></>}
function Stat({icon:I,label,value}){return <div className="stat card"><I size={19}/><span>{label}</span><b>{value}</b></div>}
function Cover({src}){return <div className="cover">{src?<img src={src} onError={e=>e.currentTarget.style.display='none'}/>:<BookOpen size={28}/>}</div>}
function BookCard({book,update,remove,edit}){return <article className="book"><Cover src={book.cover_url}/><div className="bookBody"><div className="meta"><span>{book.status==='completed'?'CONCLUÍDO':book.status==='reading'?'LENDO':'NA FILA'}</span>{book.rating&&<span className="rating"><Star size={13} fill="currentColor"/> {book.rating}</span>}</div><h3>{book.title}</h3><p>{book.author}</p>{book.total_pages&&<><div className="progressText"><b>{pct(book)}%</b><span>{book.current_page||0}/{book.total_pages}</span></div><div className="bar"><i style={{width:pct(book)+'%'}}/></div></>} {book.summary&&<div className="summary">{book.summary}</div>}<div className="actions"><button className="secondary" onClick={edit}>Editar</button>{book.status!=='completed'&&<button className="icon" title="Avançar status" onClick={()=>update(book.id,{status:book.status==='future'?'reading':'completed',current_page:book.status==='reading'&&book.total_pages?book.total_pages:book.current_page})}><CheckCircle2 size={17}/></button>}<button className="icon danger" onClick={()=>remove(book.id)}><X size={17}/></button></div></div></article>}
function Empty({tab,onAdd}){return <div className="empty card"><div className="emptyIcon"><Trophy/></div><h2>{tab==='completed'?'Ainda não há conquistas aqui.':'Sua estante está esperando.'}</h2><p>Adicione um livro e comece a construir seu histórico.</p><button className="primary" onClick={onAdd}><Plus size={17}/> Adicionar livro</button></div>}
function EmptyMini({text,onClick}){return <div className="emptyMini"><BookOpen size={30}/><p>{text}</p><button className="secondary" onClick={onClick}>Ver futuras leituras</button></div>}

function BookModal({book,close,save}){const [f,setF]=useState({title:'',author:'',isbn:'',cover_url:'',summary:'',wikipedia_url:'',total_pages:'',current_page:0,status:'future',priority:'normal',rating:'',notes:'',started_at:'',completed_at:'',...book});const set=(k,v)=>setF(x=>({...x,[k]:v}));return <div className="backdrop"><div className="modal"><div className="modalHead"><div><label>DETALHES DO LIVRO</label><h2>{book?'Editar livro':'Adicionar livro'}</h2></div><button className="icon" onClick={close}><X/></button></div><div className="modalLayout"><div className="modalCover"><Cover src={f.cover_url}/></div><div className="form"><div className="fields"><label>Título<input value={f.title||''} onChange={e=>set('title',e.target.value)}/></label><label>Autor<input value={f.author||''} onChange={e=>set('author',e.target.value)}/></label><label>Páginas<input type="number" value={f.total_pages||''} onChange={e=>set('total_pages',e.target.value)}/></label><label>Página atual<input type="number" min="0" value={f.current_page||0} onChange={e=>set('current_page',e.target.value)}/></label><label>Status<select value={f.status} onChange={e=>{const v=e.target.value;setF(x=>({...x,status:v,rating:v==='completed'?x.rating:''}))}}><option value="future">Futura leitura</option><option value="reading">Estou lendo</option><option value="completed">Concluído</option></select></label><label>Prioridade<select value={f.priority} onChange={e=>set('priority',e.target.value)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option></select></label><label>Nota (após concluir)<select value={f.rating||''} disabled={f.status!=='completed'} onChange={e=>set('rating',e.target.value)}><option value="">Sem nota</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label><label>ISBN<input value={f.isbn||''} onChange={e=>set('isbn',e.target.value)}/></label><label className="wide">Capa (URL)<input value={f.cover_url||''} onChange={e=>set('cover_url',e.target.value)}/></label><label className="wide">Resumo<textarea rows="4" value={f.summary||''} onChange={e=>set('summary',e.target.value)}/></label><label className="wide">Suas notas<textarea rows="5" value={f.notes||''} onChange={e=>set('notes',e.target.value)} placeholder="O que você achou? Ideias, citações, impressões…"/></label></div><div className="modalFoot"><button className="ghost" onClick={close}>Cancelar</button><button className="primary" onClick={()=>save(f)}>Salvar livro</button></div></div></div></div></div>}
function Auth({authMode,setAuthMode,email,setEmail,password,setPassword,authMessage,auth}){return <div className="auth"><div className="authCard"><div className="authBrand"><div className="logo"><BookOpen/></div><b>Reading Nexus</b></div><label>SEU UNIVERSO DE LEITURA</label><h1>{authMode==='login'?'Bem-vindo de volta.':'Criar sua conta.'}</h1><p>Seu histórico acompanha você em qualquer lugar.</p><form onSubmit={auth}><input type="email" placeholder="Seu e-mail" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)} required minLength="6"/><button className="primary" type="submit"><LogIn size={17}/>{authMode==='login'?'Entrar':'Criar conta'}</button></form>{authMessage&&<div className="message">{authMessage}</div>}<button className="link" onClick={()=>setAuthMode(authMode==='login'?'signup':'login')}>{authMode==='login'?'Ainda não tenho uma conta':'Já tenho uma conta'}</button><small className="authNote">Depois da configuração inicial, deixe o cadastro de novos usuários desativado.</small></div></div>}
createRoot(document.getElementById('root')).render(<App/>)
